export { default as harytlar } from '../images/harytlar.png';
export { default as kolleksiya } from '../images/kolleksiya.png';
export { default as maslahat } from '../images/maslahat.png';
export { default as Logfut } from '../images/harytlar.png';
export { default as googleplay } from '../images/googleplay.CUq9iiJj.png';
export { default as appstore } from '../images/appstore.BzQ4lsL6.png';
export { default as  apk} from '../images/apk.9ZYehQS_.png';
export { default as  tm} from '../images/tm.png';
export { default as  en} from '../images/en.png';
export { default as  ru} from '../images/ru.png';
export { default as  alma} from '../images/org_GKNGO1080_1.jpg';
export { default as  like} from '../images/Gemini_Generated_Image_48bw3k48bw3k48bw.png';
export { default as  meywe} from '../images/9000.png';
export { default as  google} from '../images/google.png';
export { default as  Apple} from '../images/Apple_logo_black.svg.png';
export { default as  Banner1} from '../images/banner1.jpg';
export { default as  Banner2} from '../images/banner2.jpg';
export { default as  Banner3} from '../images/banner3.jpg';
export { default as  Banner4} from '../images/banner4.jpg';
export { default as  Banner5} from '../images/banner5.jpg';
export { default as  Halanlarymfoto} from '../images/wishlist.BBRU2N-w.png';
export { default as  androidweioslogo} from '../images/android-ios.4g4HlG_e.png';
export { default as Sebetbosfot } from '../images/cart.CcOHzM_i.png';